import i18n from "@/i18n";

export const HujajDakhilStyleFormData = [
  {
    col: "12",
    value: "",
    object: false,
    value_text: "type_id",
    class: "form-control",
    error: null,
    required: true,
    type: "select",
    val_select: "code",
    label: i18n.t("user type"),
    class_div: "input-group auth-pass-inputgroup",
    items: [],
    rules: [(v) => !!v || i18n.t("form.Item is required")],
  },
  {
    class: "form-control",
    error: null,
    required: true,
    type: "email",
    label: i18n.t("auth.Email Address"),
    placeholder: "Example@test.com",
    class_div: "input-group auth-pass-inputgroup",
    value_text: "email",
    rules: [
      (v) => !!v || i18n.t("form.Item is required"),
      (v) =>
        (v &&
          // /^(([a-zA-Z\-0-9]+[^<>()\\.,;:@"]+(\.[a-zA-Z\-0-9]+[^<>()\\.,;:@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,24}))$/.test(
          /^(([a-zA-Z\-0-9]+(\.[a-zA-Z\-0-9]+[^<>()\\.,;:@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z0-9]+\.)+[a-zA-Z]{2,24}))$/.test(
            v
          )) ||
        i18n.t("auth.E-mail must be valid"),
    ],
  },
  {
    value_text: "company_name",
    class: "form-control",
    error: null,
    required: true,
    label: i18n.t("Company Name"),
    placeholder: i18n.t("Company Name"),
    class_div: "input-group auth-pass-inputgroup",
    rules: [(v) => !!v || i18n.t("form.Item is required")],
  },
  {
    type: "password",
    value_text: "password",
    class: "form-control",
    error: null,
    required: true,
    label: i18n.t("auth.Password"),
    placeholder: i18n.t("auth.Password"),
    show: false,
    rules: [
      (v) => !!v || i18n.t("auth.Password is required"),
      (v) =>
        (v && v.length >= 6) || i18n.t("auth.minimum 6 characters at least"),
    ],
    class_div: "input-group auth-pass-inputgroup",
  },
  {
    class_div: "input-group auth-pass-inputgroup",
    value_text: "password_confirmation",
    type: "password",
    class: "form-control",
    error: null,
    required: true,
    label: i18n.t("auth.Repeat Password"),
    placeholder: i18n.t("auth.Repeat Password"),
    show: false,
    rules: [(v) => !!v || i18n.t("auth.Password Confirmation is required")],
  },
  {
    value_text: "owner_name",
    class: "form-control",
    error: null,
    required: true,
    label: i18n.t("PossName"),
    placeholder: i18n.t("PossName"),
    class_div: "input-group auth-pass-inputgroup",
    rules: [(v) => !!v || i18n.t("form.Item is required")],
  },
  {
    type: "number",
    value_text: "commercial",
    class: "form-control",
    error: null,
    required: true,
    label: i18n.t("Commercial Register num"),
    placeholder: i18n.t("Commercial Register num"),
    class_div: "input-group auth-pass-inputgroup",
    rules: [
      (v) => !!v || i18n.t("form.Item is required"),
      (v) => (v && v.length === 10) || i18n.t("equal 10 characters"),
    ],
  },
  {
    type: "number",
    class: "form-control",
    error: null,
    required: true,
    value_text: "owner_hardcopyid",
    label: i18n.t("ID No"),
    placeholder: i18n.t("ID No"),
    class_div: "input-group auth-pass-inputgroup",
    rules: [
      (v) => !!v || i18n.t("form.Item is required"),
      (v) => /^(1)\d*$/.test(v) || i18n.t("have to start number 1"),
      (v) => (v && v.length === 10) || i18n.t("equal 10 characters"),
    ],
  },
  {
    class: "d-inline-block form-control w-80",
    required: true,
    value_text: "phone",
    type: "number",
    label: i18n.t("auth.Phone Number"),
    placeholder: "5xxxxxxxx",
    class_div: "input-group auth-pass-inputgroup",
    rules: [
      (v) => !!v || i18n.t("form.Item is required"),
      (v) => /^(5)\d*$/.test(v) || i18n.t("have to start number 5"),
      (v) => (v && v.length === 9) || i18n.t("equal 9 characters"),
    ],
  },
  {
    col: "12",
    type: "number",
    value_text: "license",
    visible: true,
    class: "form-control",
    error: null,
    required: true,
    label: i18n.t("license"),
    placeholder: i18n.t("license"),
    class_div: "input-group auth-pass-inputgroup",
    rules: [(v) => !!v || i18n.t("form.Item is required")],
  },
];
export const ContactorStyleFormData = [
  {
    col: "12",
    value: "",
    object: false,
    value_text: "type_id",
    class: "form-control",
    error: null,
    required: true,
    type: "select",
    val_select: "code",
    label: i18n.t("user type"),
    class_div: "input-group auth-pass-inputgroup",
    items: [],
    rules: [(v) => !!v || i18n.t("form.Item is required")],
  },
  {
    visible: true,
    value: "",
    col: "6",
    class: "form-control",
    error: null,
    required: true,
    class_div: "input-group auth-pass-inputgroup",
    label: i18n.t("Specialties"),
    value_text: "category_id",
    type: "select",
    items: [],
    rules: [(v) => !!v || i18n.t("form.Item is required")],
  },
  {
    value_text: "company_name",
    class: "form-control",
    error: null,
    required: true,
    label: i18n.t("Company Name"),
    placeholder: i18n.t("Company Name"),
    class_div: "input-group auth-pass-inputgroup",
    rules: [(v) => !!v || i18n.t("form.Item is required")],
  },
  {
    value_text: "owner_name",
    class: "form-control",
    error: null,
    required: true,
    label: i18n.t("PossName"),
    placeholder: i18n.t("PossName"),
    class_div: "input-group auth-pass-inputgroup",
    rules: [(v) => !!v || i18n.t("form.Item is required")],
  },
  {
    type: "number",
    class: "form-control",
    error: null,
    required: true,
    value_text: "owner_hardcopyid",
    label: i18n.t("ID No"),
    placeholder: i18n.t("ID No"),
    class_div: "input-group auth-pass-inputgroup",
    rules: [
      (v) => !!v || i18n.t("form.Item is required"),
      (v) => /^(1)\d*$/.test(v) || i18n.t("have to start number 1"),
      (v) => (v && v.length === 10) || i18n.t("equal 10 characters"),
    ],
  },
  {
    type: "number",
    value_text: "commercial",
    class: "form-control",
    error: null,
    required: true,
    label: i18n.t("Commercial Register num"),
    placeholder: i18n.t("Commercial Register num"),
    class_div: "input-group auth-pass-inputgroup",
    rules: [
      (v) => !!v || i18n.t("form.Item is required"),
      (v) => (v && v.length === 10) || i18n.t("equal 10 characters"),
    ],
  },
  {
    class: "form-control",
    error: null,
    required: true,
    type: "email",
    label: i18n.t("auth.Email Address"),
    placeholder: "Example@test.com",
    class_div: "input-group auth-pass-inputgroup",
    value_text: "email",
    rules: [
      (v) => !!v || i18n.t("form.Item is required"),
      (v) =>
        (v &&
          // /^(([a-zA-Z\-0-9]+[^<>()\\.,;:@"]+(\.[a-zA-Z\-0-9]+[^<>()\\.,;:@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,24}))$/.test(
          /^(([a-zA-Z\-0-9]+(\.[a-zA-Z\-0-9]+[^<>()\\.,;:@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z0-9]+\.)+[a-zA-Z]{2,24}))$/.test(
            v
          )) ||
        i18n.t("auth.E-mail must be valid"),
    ],
  },
  {
    class: "d-inline-block form-control w-80",
    required: true,
    value_text: "phone",
    type: "number",
    label: i18n.t("auth.Phone Number"),
    placeholder: "5xxxxxxxx",
    class_div: "input-group auth-pass-inputgroup",
    rules: [
      (v) => !!v || i18n.t("form.Item is required"),
      (v) => /^(5)\d*$/.test(v) || i18n.t("have to start number 5"),
      (v) => (v && v.length === 9) || i18n.t("equal 9 characters"),
    ],
  },
  {
    value_text: "city_id",
    visible: true,
    class: "form-control",
    error: null,
    required: true,
    type: "select",
    label: i18n.t("city"),
    placeholder: i18n.t("city"),
    class_div: "input-group auth-pass-inputgroup",
    items: [],
    rules: [(v) => !!v || i18n.t("form.Item is required")],
  },
  {
    type: "password",
    value_text: "password",
    class: "form-control",
    error: null,
    required: true,
    label: i18n.t("auth.Password"),
    placeholder: i18n.t("auth.Password"),
    show: false,
    rules: [
      (v) => !!v || i18n.t("auth.Password is required"),
      (v) =>
        (v && v.length >= 6) || i18n.t("auth.minimum 6 characters at least"),
    ],
    class_div: "input-group auth-pass-inputgroup",
  },
  {
    class_div: "input-group auth-pass-inputgroup",
    value_text: "password_confirmation",
    type: "password",
    class: "form-control",
    error: null,
    required: true,
    label: i18n.t("auth.Repeat Password"),
    placeholder: i18n.t("auth.Repeat Password"),
    show: false,
    rules: [(v) => !!v || i18n.t("auth.Password Confirmation is required")],
  },
];
export const DesignOfficeStyleFormData = [
  {
    col: "12",
    value: "",
    object: false,
    value_text: "type_id",
    class: "form-control",
    error: null,
    required: true,
    type: "select",
    val_select: "code",
    label: i18n.t("user type"),
    class_div: "input-group auth-pass-inputgroup",
    items: [],
    rules: [(v) => !!v || i18n.t("form.Item is required")],
  },
  {
    visible: true,
    value: "",
    col: "6",
    class: "form-control",
    error: null,
    required: true,
    class_div: "input-group auth-pass-inputgroup",
    label: i18n.t("Specialties"),
    value_text: "category_id",
    type: "select",
    items: [],
    rules: [(v) => !!v || i18n.t("form.Item is required")],
  },
  {
    value_text: "company_name",
    class: "form-control",
    error: null,
    required: true,
    label: i18n.t("Company Name"),
    placeholder: i18n.t("Company Name"),
    class_div: "input-group auth-pass-inputgroup",
    rules: [(v) => !!v || i18n.t("form.Item is required")],
  },
  {
    value_text: "owner_name",
    class: "form-control",
    error: null,
    required: true,
    label: i18n.t("PossName"),
    placeholder: i18n.t("PossName"),
    class_div: "input-group auth-pass-inputgroup",
    rules: [(v) => !!v || i18n.t("form.Item is required")],
  },
  {
    type: "number",
    class: "form-control",
    error: null,
    required: true,
    value_text: "owner_hardcopyid",
    label: i18n.t("ID No"),
    placeholder: i18n.t("ID No"),
    class_div: "input-group auth-pass-inputgroup",
    rules: [
      (v) => !!v || i18n.t("form.Item is required"),
      (v) => /^(1)\d*$/.test(v) || i18n.t("have to start number 1"),
      (v) => (v && v.length === 10) || i18n.t("equal 10 characters"),
    ],
  },
  {
    type: "number",
    value_text: "commercial",
    class: "form-control",
    error: null,
    required: true,
    label: i18n.t("Commercial Register num"),
    placeholder: i18n.t("Commercial Register num"),
    class_div: "input-group auth-pass-inputgroup",
    rules: [
      (v) => !!v || i18n.t("form.Item is required"),
      (v) => (v && v.length === 10) || i18n.t("equal 10 characters"),
    ],
  },
  {
    class: "form-control",
    error: null,
    required: true,
    type: "email",
    label: i18n.t("auth.Email Address"),
    placeholder: "Example@test.com",
    class_div: "input-group auth-pass-inputgroup",
    value_text: "email",
    rules: [
      (v) => !!v || i18n.t("form.Item is required"),
      (v) =>
        (v &&
          // /^(([a-zA-Z\-0-9]+[^<>()\\.,;:@"]+(\.[a-zA-Z\-0-9]+[^<>()\\.,;:@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,24}))$/.test(
          /^(([a-zA-Z\-0-9]+(\.[a-zA-Z\-0-9]+[^<>()\\.,;:@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z0-9]+\.)+[a-zA-Z]{2,24}))$/.test(
            v
          )) ||
        i18n.t("auth.E-mail must be valid"),
    ],
  },
  {
    class: "d-inline-block form-control w-80",
    required: true,
    value_text: "phone",
    type: "number",
    label: i18n.t("auth.Phone Number"),
    placeholder: "5xxxxxxxx",
    class_div: "input-group auth-pass-inputgroup",
    rules: [
      (v) => !!v || i18n.t("form.Item is required"),
      (v) => /^(5)\d*$/.test(v) || i18n.t("have to start number 5"),
      (v) => (v && v.length === 9) || i18n.t("equal 9 characters"),
    ],
  },
  {
    value_text: "city_id",
    visible: true,
    class: "form-control",
    error: null,
    required: true,
    type: "select",
    label: i18n.t("city"),
    placeholder: i18n.t("city"),
    class_div: "input-group auth-pass-inputgroup",
    items: [],
    rules: [(v) => !!v || i18n.t("form.Item is required")],
  },
  {
    type: "password",
    value_text: "password",
    class: "form-control",
    error: null,
    required: true,
    label: i18n.t("auth.Password"),
    placeholder: i18n.t("auth.Password"),
    show: false,
    rules: [
      (v) => !!v || i18n.t("auth.Password is required"),
      (v) =>
        (v && v.length >= 6) || i18n.t("auth.minimum 6 characters at least"),
    ],
    class_div: "input-group auth-pass-inputgroup",
  },
  {
    class_div: "input-group auth-pass-inputgroup",
    value_text: "password_confirmation",
    type: "password",
    class: "form-control",
    error: null,
    required: true,
    label: i18n.t("auth.Repeat Password"),
    placeholder: i18n.t("auth.Repeat Password"),
    show: false,
    rules: [(v) => !!v || i18n.t("auth.Password Confirmation is required")],
  },
];
